class Iso_Codes
  def initialize
    stuff_codes
  end

  def get_all_codes
    return @iso_codes
  end

  def stuff_codes
      @iso_codes = Array.new
      @iso_codes << 'AC - Ascension Island'
      @iso_codes << 'AD - Andorra'
      @iso_codes << 'AE - United Arab Emirates'
      @iso_codes << 'AF - Afghanistan'
      @iso_codes << 'AG - Antigua and Barbuda'
      @iso_codes << 'AI - Anguilla'
      @iso_codes << 'AL - Albania'
      @iso_codes << 'AM - Armenia'
      @iso_codes << 'AN - Netherlands Antilles'
      @iso_codes << 'AO - Angola'
      @iso_codes << 'AQ - Antarctica'
      @iso_codes << 'AR - Argentina'
      @iso_codes << 'AS - American Samoa'
      @iso_codes << 'AT - Austria'
      @iso_codes << 'AU - Australia'
      @iso_codes << 'AW - Aruba'
      @iso_codes << 'AX - Aland Islands'
      @iso_codes << 'AZ - Azerbaijan'
      @iso_codes << 'BA - Bosnia and Herzegovina'
      @iso_codes << 'BB - Barbados'
      @iso_codes << 'BD - Bangladesh'
      @iso_codes << 'BE - Belgium'
      @iso_codes << 'BF - Burkina Faso'
      @iso_codes << 'BG - Bulgaria'
      @iso_codes << 'BH - Bahrain'
      @iso_codes << 'BI - Burundi'
      @iso_codes << 'BJ - Benin'
      @iso_codes << 'BM - Bermuda'
      @iso_codes << 'BN - Brunei Darussalam'
      @iso_codes << 'BO - Bolivia'
      @iso_codes << 'BR - Brazil'
      @iso_codes << 'BS - Bahamas'
      @iso_codes << 'BT - Bhutan'
      @iso_codes << 'BV - Bouvet Island'
      @iso_codes << 'BW - Botswana'
      @iso_codes << 'BY - Belarus'
      @iso_codes << 'BZ - Belize'
      @iso_codes << 'CA - Canada'
      @iso_codes << 'CC - Cocos (Keeling) Islands'
      @iso_codes << 'CD - Congo, Democratic Republic'
      @iso_codes << 'CF - Central African Republic'
      @iso_codes << 'CG - Congo'
      @iso_codes << 'CH - Switzerland'
      @iso_codes << 'CI - Cote D\'Ivoire (Ivory Coast)'
      @iso_codes << 'CK - Cook Islands'
      @iso_codes << 'CL - Chile'
      @iso_codes << 'CM - Cameroon'
      @iso_codes << 'CN - China'
      @iso_codes << 'CO - Colombia'
      @iso_codes << 'CR - Costa Rica'
      @iso_codes << 'CS - Czechoslovakia (former)'
      @iso_codes << 'CU - Cuba'
      @iso_codes << 'CV - Cape Verde'
      @iso_codes << 'CX - Christmas Island'
      @iso_codes << 'CY - Cyprus'
      @iso_codes << 'CZ - Czech Republic'
      @iso_codes << 'DE - Germany'
      @iso_codes << 'DJ - Djibouti'
      @iso_codes << 'DK - Denmark'
      @iso_codes << 'DM - Dominica'
      @iso_codes << 'DO - Dominican Republic'
      @iso_codes << 'DZ - Algeria'
      @iso_codes << 'EC - Ecuador'
      @iso_codes << 'EE - Estonia'
      @iso_codes << 'EG - Egypt'
      @iso_codes << 'EH - Western Sahara'
      @iso_codes << 'ER - Eritrea'
      @iso_codes << 'ES - Spain'
      @iso_codes << 'ET - Ethiopia'
      @iso_codes << 'FI - Finland'
      @iso_codes << 'FJ - Fiji'
      @iso_codes << 'FK - Falkland Islands (Malvinas)'
      @iso_codes << 'FM - Micronesia'
      @iso_codes << 'FO - Faroe Islands'
      @iso_codes << 'FR - France'
      @iso_codes << 'FX - France, Metropolitan'
      @iso_codes << 'GA - Gabon'
      @iso_codes << 'GB - Great Britain (UK)'
      @iso_codes << 'GD - Grenada'
      @iso_codes << 'GE - Georgia'
      @iso_codes << 'GF - French Guiana'
      @iso_codes << 'GG - Guernsey'
      @iso_codes << 'GH - Ghana'
      @iso_codes << 'GI - Gibraltar'
      @iso_codes << 'GL - Greenland'
      @iso_codes << 'GM - Gambia'
      @iso_codes << 'GN - Guinea'
      @iso_codes << 'GP - Guadeloupe'
      @iso_codes << 'GQ - Equatorial Guinea'
      @iso_codes << 'GR - Greece'
      @iso_codes << 'GS - S. Georgia and S. Sandwich Isls.'
      @iso_codes << 'GT - Guatemala'
      @iso_codes << 'GU - Guam'
      @iso_codes << 'GW - Guinea-Bissau'
      @iso_codes << 'GY - Guyana'
      @iso_codes << 'HK - Hong Kong'
      @iso_codes << 'HM - Heard and McDonald Islands'
      @iso_codes << 'HN - Honduras'
      @iso_codes << 'HR - Croatia (Hrvatska)'
      @iso_codes << 'HT - Haiti'
      @iso_codes << 'HU - Hungary'
      @iso_codes << 'ID - Indonesia'
      @iso_codes << 'IE - Ireland'
      @iso_codes << 'IL - Israel'
      @iso_codes << 'IM - Isle of Man'
      @iso_codes << 'IN - India'
      @iso_codes << 'IO - British Indian Ocean Territory'
      @iso_codes << 'IQ - Iraq'
      @iso_codes << 'IR - Iran'
      @iso_codes << 'IS - Iceland'
      @iso_codes << 'IT - Italy'
      @iso_codes << 'JE - Jersey'
      @iso_codes << 'JM - Jamaica'
      @iso_codes << 'JO - Jordan'
      @iso_codes << 'JP - Japan'
      @iso_codes << 'KE - Kenya'
      @iso_codes << 'KG - Kyrgyzstan'
      @iso_codes << 'KH - Cambodia'
      @iso_codes << 'KI - Kiribati'
      @iso_codes << 'KM - Comoros'
      @iso_codes << 'KN - Saint Kitts and Nevis'
      @iso_codes << 'KP - Korea (North)'
      @iso_codes << 'KR - Korea (South)'
      @iso_codes << 'KW - Kuwait'
      @iso_codes << 'KY - Cayman Islands'
      @iso_codes << 'KZ - Kazakhstan'
      @iso_codes << 'LA - Laos'
      @iso_codes << 'LB - Lebanon'
      @iso_codes << 'LC - Saint Lucia'
      @iso_codes << 'LI - Liechtenstein'
      @iso_codes << 'LK - Sri Lanka'
      @iso_codes << 'LR - Liberia'
      @iso_codes << 'LS - Lesotho'
      @iso_codes << 'LT - Lithuania'
      @iso_codes << 'LU - Luxembourg'
      @iso_codes << 'LV - Latvia'
      @iso_codes << 'LY - Libya'
      @iso_codes << 'MA - Morocco'
      @iso_codes << 'MC - Monaco'
      @iso_codes << 'MD - Moldova'
      @iso_codes << 'ME - Montenegro'
      @iso_codes << 'MG - Madagascar'
      @iso_codes << 'MH - Marshall Islands'
      @iso_codes << 'MK - F.Y.R.O.M. (Macedonia)'
      @iso_codes << 'ML - Mali'
      @iso_codes << 'MM - Myanmar'
      @iso_codes << 'MN - Mongolia'
      @iso_codes << 'MO - Macau'
      @iso_codes << 'MP - Northern Mariana Islands'
      @iso_codes << 'MQ - Martinique'
      @iso_codes << 'MR - Mauritania'
      @iso_codes << 'MS - Montserrat'
      @iso_codes << 'MT - Malta'
      @iso_codes << 'MU - Mauritius'
      @iso_codes << 'MV - Maldives'
      @iso_codes << 'MW - Malawi'
      @iso_codes << 'MX - Mexico'
      @iso_codes << 'MY - Malaysia'
      @iso_codes << 'MZ - Mozambique'
      @iso_codes << 'NA - Namibia'
      @iso_codes << 'NC - New Caledonia'
      @iso_codes << 'NE - Niger'
      @iso_codes << 'NF - Norfolk Island'
      @iso_codes << 'NG - Nigeria'
      @iso_codes << 'NI - Nicaragua'
      @iso_codes << 'NL - Netherlands'
      @iso_codes << 'NO - Norway'
      @iso_codes << 'NP - Nepal'
      @iso_codes << 'NR - Nauru'
      @iso_codes << 'NT - Neutral Zone'
      @iso_codes << 'NU - Niue'
      @iso_codes << 'NZ - New Zealand (Aotearoa)'
      @iso_codes << 'OM - Oman'
      @iso_codes << 'PA - Panama'
      @iso_codes << 'PE - Peru'
      @iso_codes << 'PF - French Polynesia'
      @iso_codes << 'PG - Papua New Guinea'
      @iso_codes << 'PH - Philippines'
      @iso_codes << 'PK - Pakistan'
      @iso_codes << 'PL - Poland'
      @iso_codes << 'PM - St. Pierre and Miquelon'
      @iso_codes << 'PN - Pitcairn'
      @iso_codes << 'PR - Puerto Rico'
      @iso_codes << 'PS - Palestinian Territory, Occupied'
      @iso_codes << 'PT - Portugal'
      @iso_codes << 'PW - Palau'
      @iso_codes << 'PY - Paraguay'
      @iso_codes << 'QA - Qatar'
      @iso_codes << 'RE - Reunion'
      @iso_codes << 'RO - Romania'
      @iso_codes << 'RS - Serbia'
      @iso_codes << 'RU - Russian Federation'
      @iso_codes << 'RW - Rwanda'
      @iso_codes << 'SA - Saudi Arabia'
      @iso_codes << 'SB - Solomon Islands'
      @iso_codes << 'SC - Seychelles'
      @iso_codes << 'SD - Sudan'
      @iso_codes << 'SE - Sweden'
      @iso_codes << 'SG - Singapore'
      @iso_codes << 'SH - St. Helena'
      @iso_codes << 'SI - Slovenia'
      @iso_codes << 'SJ - Svalbard & Jan Mayen Islands'
      @iso_codes << 'SK - Slovak Republic'
      @iso_codes << 'SL - Sierra Leone'
      @iso_codes << 'SM - San Marino'
      @iso_codes << 'SN - Senegal'
      @iso_codes << 'SO - Somalia'
      @iso_codes << 'SR - Suriname'
      @iso_codes << 'ST - Sao Tome and Principe'
      @iso_codes << 'SU - USSR (former)'
      @iso_codes << 'SV - El Salvador'
      @iso_codes << 'SY - Syria'
      @iso_codes << 'SZ - Swaziland'
      @iso_codes << 'TC - Turks and Caicos Islands'
      @iso_codes << 'TD - Chad'
      @iso_codes << 'TF - French Southern Territories'
      @iso_codes << 'TG - Togo'
      @iso_codes << 'TH - Thailand'
      @iso_codes << 'TJ - Tajikistan'
      @iso_codes << 'TK - Tokelau'
      @iso_codes << 'TM - Turkmenistan'
      @iso_codes << 'TN - Tunisia'
      @iso_codes << 'TO - Tonga'
      @iso_codes << 'TP - East Timor'
      @iso_codes << 'TR - Turkey'
      @iso_codes << 'TT - Trinidad and Tobago'
      @iso_codes << 'TV - Tuvalu'
      @iso_codes << 'TW - Taiwan'
      @iso_codes << 'TZ - Tanzania'
      @iso_codes << 'UA - Ukraine'
      @iso_codes << 'UG - Uganda'
      @iso_codes << 'UK - United Kingdom'
      @iso_codes << 'UM - US Minor Outlying Islands'
      @iso_codes << 'US - United States'
      @iso_codes << 'UY - Uruguay'
      @iso_codes << 'UZ - Uzbekistan'
      @iso_codes << 'VA - Vatican City State (Holy See)'
      @iso_codes << 'VC - Saint Vincent & the Grenadines'
      @iso_codes << 'VE - Venezuela'
      @iso_codes << 'VG - British Virgin Islands'
      @iso_codes << 'VI - Virgin Islands (U.S.)'
      @iso_codes << 'VN - Viet Nam'
      @iso_codes << 'VU - Vanuatu'
      @iso_codes << 'WF - Wallis and Futuna Islands'
      @iso_codes << 'WS - Samoa'
      @iso_codes << 'XK - Kosovo'
      @iso_codes << 'YE - Yemen'
      @iso_codes << 'YT - Mayotte'
      @iso_codes << 'YU - Yugoslavia (former)'
      @iso_codes << 'ZA - South Africa'
      @iso_codes << 'ZM - Zambia'
    end
end